<div class="page-title">
    <h1 style="margin-bottom: 9px;">Contacto</h1>
</div>
<div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <h3 style="margin-top: 0; margin-bottom: 11px;">Información de contacto</h3>
        <p><strong>The Mimosa Company</strong></p>
        <p>(Parte de <strong>Conexión Mexicana B.V.</strong>)</p>
        <p>Número de registro en la Cámara de Comercio: 70576769</p>
        <p style="margin-bottom: 60px;">Número de IVA: NL858380559B01</p>
        <p>Ubicación (no disponemos de atención al público):&nbsp;</p>
        <p>Wolbrantskerkweg 65, 1069CL</p>
        <p style="margin-bottom: 13px;">Ámsterdam - Paises Bajos</p>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <h4 style="margin-bottom: 9px; margin-top: 3px;">¿Preguntas o comentarios?</h4>
        <p>Para ayudarle correctamente le aconsejamos que contacte con nosotros mediante correo electrónico. De esta manera podemos proporcionarle directamente la información adecuada. Tratamos de responder a todas las consultas en el plazo de 1 día laborable.</p>
        <p>En caso de que prefiera tener contacto por teléfono, lo más conveniente sería que nosotros le llamemos. Para solicitar una llamada, debería simplemente rellenar el formulario siguiente, y trataremos por todos los medios de llamarle en el plazo de 1 día laborable.</p>
        <p>Por supuesto, también puede usted llamarnos directamente, aunque debemos advertir que no siempre estamos disponibles. Por favor, si es así, puede dejarnos un mensaje en el buzón de voz y nosotros lo contactaremos lo antes posible.</p>
        <p>Dirección de correo electrónico: info@mimosacompany.com</p>
        <p>Teléfono: +31 (0) 85 - 208 38 00</p>
        <p style="margin-bottom: 13px;"><strong>¡Esperamos su contacto!</strong></p>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12"><img src="{{media url=&quot;wysiwyg/MimosaCo-ReDesign_Desktop_05-Contact-page.jpg&quot;}}"alt="The Mimosa Company - Contact page" width="604px" /></div>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <h4 style="color: #95609b; margin-top: 0; margin-bottom: 12px;">The Mimosa Company Team</h4>
        {{widget type="Amasty\Customform\Block\Init" template="init.phtml" form_id="8"}}</div>
</div>