<div class="page-title">
    <h1>Contacto</h1>
</div>
<div class="col3-set row">
    <div class="col-6">
        <p style="text-align: justify;"><span style="color: #000000;"><strong>Información de contacto</strong></span></p>
        <p style="text-align: justify;"><span style="color: #95609b;"><strong>The Mimosa Company</strong></span></p>
        <p style="text-align: justify;">(Parte de <strong>Conexión Mexicana B.V.</strong>)</p>
        <p style="text-align: justify;">Número de registro en la Cámara de Comercio: 70576769</p>
        <p style="text-align: justify;">Número de IVA: NL858380559B01</p>
        <p style="text-align: justify;"><strong>Ubicación (no disponemos de atención al público):</strong></p>
        <p style="text-align: justify;">Wolbrantskerkweg 65, 1069CL</p>
        <p style="text-align: justify;">Ámsterdam - Paises Bajos</p>
        <p style="text-align: justify;">&nbsp;</p>
        <p style="text-align: justify;"><span style="color: #000000;"><strong>¿Preguntas o comentarios?</strong></span></p>
        <p style="text-align: justify;">Para ayudarle correctamente le aconsejamos que contacte con nosotros mediante correo electrónico. De esta manera podemos proporcionarle directamente la información adecuada. Tratamos de responder a todas las consultas en el plazo de 1 día laborable.</p>
    </div>
    <div class="col-6">
        <p style="text-align: justify;">En caso de que prefiera tener contacto por teléfono, lo más conveniente sería que nosotros le llamemos. Para solicitar una llamada, debería simplemente rellenar el formulario siguiente, y trataremos por todos los medios de llamarle en el plazo de 1 día laborable.</p>
        <p style="text-align: justify;">Por supuesto, también puede usted llamarnos directamente, aunque debemos advertir que no siempre estamos disponibles. Por favor, si es así, puede dejarnos un mensaje en el buzón de voz y nosotros lo contactaremos lo antes posible.</p>
        <p style="text-align: justify;">Dirección de correo electrónico: info@mimosacompany.com</p>
        <p style="text-align: justify;">Teléfono: +31 (0) 85 - 208 38 00</p>
        <p style="text-align: justify;"><span style="color: #000000;"><strong>¡Esperamos su contacto!</strong></span></p>
        <p style="line-height: 1.2em;"><strong style="font: italic 2em Georgia, serif;">The Mimosa Company Team</strong></p>
        <div class="divider" style="text-align: justify;">&nbsp;</div>
    </div>
    <div class="col-12">{{widget type="Amasty\Customform\Block\Init" template="init.phtml" form_id="8"}}</div>
</div>