<div class="page-title">
    <h1 style="margin-bottom: 9px;">Contact</h1>
</div>
<div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <h3 style="margin-top: 0; margin-bottom: 11px;">Contact details</h3>
        <p><strong>The Mimosa Company</strong></p>
        <p>(Part of Conexión Mexicana B.V.)</p>
        <p>KvK number: 70576769</p>
        <p style="margin-bottom: 60px;">VAT-number: NL858380559B01</p>
        <p>Location (No visiting address!):&nbsp;</p>
        <p>Wolbrantskerkweg 65, 1069CL</p>
        <p style="margin-bottom: 13px;">Amsterdam - The Netherlands</p>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <h4 style="margin-bottom: 9px; margin-top: 3px;">Questions?</h4>
        <p>To help you properly we advise you to contact us by e-mail. This way we can directly provide you with the correct information. We try to respond to all queries within 1 business day.</p>
        <p>If you prefer to get in contact by telephone. We preferably call you back. To request a call, you should only fill out the form below and we will do our best to make sure to call you within 1 business day.</p>
        <p>Of course, you can also contact us by phone, however, we are not always available. Please feel free to take the opportunity to leave a voicemail. We will always try to contact you as soon as possible.</p>
        <p>E-mail address: info@mimosacompany.com</p>
        <p>Phone number: +31 (0) 85 - 208 38 00</p>
        <p style="margin-bottom: 13px;"><strong>We would love to hear from you!</strong></p>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12"><img src="{{media url=&quot;wysiwyg/MimosaCo-ReDesign_Desktop_05-Contact-page.jpg&quot;}}"alt="The Mimosa Company - Contact page" width="604px" /></div>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <h4 style="color: #95609b; margin-top: 0; margin-bottom: 12px;">The Mimosa Company Team</h4>
        {{widget type="Amasty\Customform\Block\Init" template="init.phtml" form_id="1"}}</div>
</div>