<div id="shipping">
    <h4>Shipping within The Netherlands</h4>
    <p>All prices on our webshop are exclusive of shipping costs.&nbsp;<strong>Shipping within The Netherlands amounts:</strong></p>
    &nbsp;
    <p><strong>€6,95 </strong>for a standard package</p>
    &nbsp;
    <p><strong>€7.50 </strong>for a registered package</p>
    &nbsp;
    <p><strong>Delivery time within the Netherlands</strong></p>
    <p>We do our best to carefully deliver orders as soon as possible. Orders placed on working days before 22:00 hours are shipped on the same day. We do not always succeed to fulfil this, but will in any case dispatch your order within 24 hours. Should we, for one reason or another, not meet the delivery time, we will obviously notify you as soon as possible.</p>
    <p><strong>Delivery elapses via the postman or parcel delivery of Post NL</strong>. After placing your order, you will receive an email with the track &amp; trace code, with which you can follow your shipment.</p>
    <p>The delivery time varies between 1 to 2 business days, but in general, orders are delivered the following business day between 9:00 and 18:00. Unfortunately, we cannot guarantee the exact time of delivery.&nbsp;</p>
    <p>Please note that PostNL delivers (packages) from Tuesday to Saturday.</p>
    <p>&nbsp;</p>
    <table style="margin-left: auto; margin-right: auto;" border="4">
        <thead>
        <tr>
            <th scope="row"><strong>Posted on:</strong></th>
            <th><strong>Delivered before 18.00 on:&nbsp;</strong></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Monday</td>
            <td>Tuesday</td>
        </tr>
        <tr>
            <td>Tuesday</td>
            <td>Wednesday</td>
        </tr>
        <tr>
            <td>Wednesday</td>
            <td>Thursday</td>
        </tr>
        <tr>
            <td>Thursday</td>
            <td>Friday</td>
        </tr>
        <tr>
            <td>Friday</td>
            <td>Saturday</td>
        </tr>
        <tr>
            <td>Saturday</td>
            <td>Tuesday</td>
        </tr>
        <tr>
            <td>Sunday</td>
            <td>Tuesday</td>
        </tr>
        </tbody>
    </table>
    <p>&nbsp;</p>
    <p><strong>International shipping and delivery times</strong></p>
    <p>The shipping costs for international orders vary per destination. The maximum weight per package is 30kg. In the event of outpacing the maximum weight, extra shipping costs apply. All international shipments are registered via the common procedure and insurance sent with the associated track &amp; trace code of PostNL.</p>
    <p>&nbsp;</p>
    <table style="margin-left: auto; margin-right: auto;" border="2">
        <thead>
        <tr>
            <th scope="row"><strong>Destination</strong></th>
            <th><strong>Shipping costs in euro (€)</strong></th>
            <th><strong>Delivery time in days</strong></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Belgium</td>
            <td>10.00</td>
            <td>1-2</td>
        </tr>
        <tr>
            <td>Bulgaria</td>
            <td>28.00</td>
            <td>5</td>
        </tr>
        <tr>
            <td>Denmark</td>
            <td>18.50</td>
            <td>3-4</td>
        </tr>
        <tr>
            <td>Germany</td>
            <td>10.00</td>
            <td>1-2</td>
        </tr>
        <tr>
            <td>Estonia</td>
            <td>29.00</td>
            <td>4-5</td>
        </tr>
        <tr>
            <td>Finland</td>
            <td>23.50</td>
            <td>4-5</td>
        </tr>
        <tr>
            <td>Great Britain</td>
            <td>14.00</td>
            <td>2-3</td>
        </tr>
        <tr>
            <td>Hungary</td>
            <td>25.00</td>
            <td>3-5</td>
        </tr>
        <tr>
            <td>Ireland</td>
            <td>24.00</td>
            <td>3-4</td>
        </tr>
        <tr>
            <td>Italy</td>
            <td>18.50</td>
            <td>3-4</td>
        </tr>
        <tr>
            <td>Latvia</td>
            <td>29.00</td>
            <td>4-5</td>
        </tr>
        <tr>
            <td>Lithuania</td>
            <td>29.00</td>
            <td>4-5</td>
        </tr>
        <tr>
            <td>Luxembourg</td>
            <td>14.00</td>
            <td>2</td>
        </tr>
        <tr>
            <td>Austria</td>
            <td>18.50</td>
            <td>2-4</td>
        </tr>
        <tr>
            <td>Poland</td>
            <td>25.00</td>
            <td>3-4</td>
        </tr>
        <tr>
            <td>Portugal</td>
            <td>23.00</td>
            <td>3-5</td>
        </tr>
        <tr>
            <td>Slovenia</td>
            <td>25.00</td>
            <td>4-5</td>
        </tr>
        <tr>
            <td>Slovak Republic</td>
            <td>25.00</td>
            <td>3-5</td>
        </tr>
        <tr>
            <td>Spain</td>
            <td>23.00</td>
            <td>3-5</td>
        </tr>
        <tr>
            <td>Czech Republic</td>
            <td>25.00</td>
            <td>3-5</td>
        </tr>
        <tr>
            <td>Sweden</td>
            <td>24.00</td>
            <td>2-4</td>
        </tr>
        <tr>
            <td>Norway</td>
            <td>28.00</td>
            <td>2-4</td>
        </tr>
        <tr>
            <td>Switzerland</td>
            <td>28.00</td>
            <td>2-3</td>
        </tr>
        <tr>
            <td>Rest of Europa</td>
            <td>28.00</td>
            <td>3-5</td>
        </tr>
        </tbody>
    </table>
    &nbsp;
    <p>* For more and other international destinations: please contact us to request a quote.</p>
</div>
<div id="payment">
    <h2><span style="color: #000000;"><a style="color: #000000;" href="https://www.mimosacompany.com/payment-methods">Payment methods</a></span></h2>
    <h4>How can I pay for my order?</h4>
    <p>You can place your order with several payment methods. Currently, we offer the following payment methods:</p>
    <ul>
        <li><strong>Ideal</strong></li>
        <li><strong>Sofort</strong></li>
        <li><strong>GiroPay</strong></li>
        <li><strong>Bancontant / Mister Cash</strong></li>
    </ul>
</div>
<div id="warranty">
    <h2><span style="color: #000000;"><a style="color: #000000;" href="https://www.mimosacompany.com/warranty-complaints">Warranty and complaints</a></span></h2>
    <h4>Warranty</h4>
    <p>We care about our products and do our best to deliver our goods in top condition. However, it occurs that products break during transportation or something else happens which entitle you to make a claim. You are legally obliged to notify us within two months after finding the lack. If the deficiency meets the warranty, we will take care of the replacement free of charge.</p>
    <h4>Complaints procedure</h4>
    <p>We advise you to first declare your complaint by emailing: <strong>info@mimosacompany.com</strong>. If this does not lead to a solution, it is possible to notify your dispute for conciliation at <strong>Stichting WebwinkelKeur</strong>. From the 15th of February 2016, consumers in the EU can also register complaints via the ODR platform of the European Commission. This ODR platform can be found on <strong>http://ec.europa.eu/odr</strong>. When your complaint not yet elsewhere is conducted, you are free to deposit your complaint through the platform of the European Union.</p>
</div>
<div id="returns">
    <h2><a href="https://www.mimosacompany.com/returns"><span style="color: #000000;">Returns</span></a></h2>
    <h4>Cooling-off period / Returns</h4>
    <p>Occasionally, you may want to return an order. Perhaps because the product did not meet your wishes or another reason why you no longer wish the good. We ask you to consider the following rules regarding the returns of orders with The Mimosa Company:</p>
    <ol>
        <li>The&nbsp;<strong>food products</strong>&nbsp;you purchase through this online store have a limited shelf life and can therefore not be returned. The right of return is not applicable. After successful payment, the sale is therefore a fact.</li>
        <li>For&nbsp;<strong>products not covered by the food category, </strong>&nbsp;you can make use of the right of withdrawal. For these products, you have the right to cancel the order within 14 days after receipt without giving any reason. After cancellation, you have once again, 14 days to return your product.</li>
    </ol>
    <p>When returning a complete order, you get the full refund of the purchase including shipping costs. Only the expenses for the return of your home to the online store are for your own account. These costs amount to approximately €6,95 per package. Refer to the website of your carrier for the exact rates.</p>
    <p>If you only return part of the order, you will get a refund of the value of the returned articles excluding shipping costs. If you exercise your right of withdrawal, the product must be returned with all accessories and - as reasonable as possible - in the original condition and packaging to The Mimosa Company. To make use of this right you must complete the <span style="text-decoration: underline;"><strong><a title="Withdrawal Form" href="{{media url=" documents/Withdrawal_form_The_Mimosa_Company_English.pdf"}}" target="_blank" rel="noopener" download="download">standard withdrawal form</a></strong></span> and send this to us via <strong>info@mimosacompany.com</strong>. We will then pay the purchase amount within 14 days after the registration of your return, provided that the product is received accurately.&nbsp;</p>
    <p>If a product is damaged or the packaging is impaired more than is necessary in order to try the product, we will calculate a reduction in the value of the product for your account. For this reason, take care of the good and ensure that, in the event of a return, the product is packed properly.</p>
    <p><strong>I have submitted an incorrect delivery address</strong></p>
    <p>Accidentally passed on an incorrect delivery address? Please contact us as soon as possible. We will then try to change the order as soon as possible.</p>
</div>