<div id="shipping">
    <h4>Servicio al cliente</h4>

    <p><strong>Envío dentro de los Países Bajos</strong></p>

    <p>Todos los precios de nuestra tienda online no incluyen los gastos de envío. <strong>El coste del envío dentro de los Países Bajos es de:</strong></p>
    &nbsp;
    <p><strong>€4,50 </strong>para un paquete tamaño buzón</p>
    &nbsp;
    <p><strong>€6,95 </strong>para un paquete estándar</p>
    &nbsp;
    <p><strong>€7.50 </strong>para un paquete certificado</p>
    &nbsp;
    <p><strong>Plazo de entrega dentro de los Países Bajos</strong></p>
    <p>Hacemos todo lo posible para enviar rápida y cuidadosamente cada pedido. Tratamos de hacer los envíos de los pedidos que se hayan hecho en días laborables antes de las 15:00pm en el mismo día. No siempre podemos conseguirlo, pero en cualquier caso siempre enviaremos su pedido en el plazo de 24 horas. Si, por circunstancias extraordinarias, no pudiéramos cumplir nuestra promesa, entonces obviamente le informaríamos tan pronto como nos fuera posible.</p>
    <p><strong>La entrega se realizará a través del servicio postal o paquetería de Post NL.</strong> Tras hacer su pedido, recibirá un correo electrónico con el número de seguimiento, con el cual podrá seguir la evolución de su envío.</p>
    <p>El tiempo de entrega varía entre 1 o 2 días laborables, pero en general, los pedidos se reciben al día siguiente laborable, entre las 9:00 y las 18:00 horas. Desafortunadamente, no podemos especificar la hora exacta de la entrega.</p>
    <p>Por favor, tenga en cuenta que Post NL entrega la paquetería de martes a sábado.</p>
    <p>&nbsp;</p>
    <table style="margin-left: auto; margin-right: auto;" border="4">
        <thead>
        <tr>
            <th scope="row"><strong>Enviado el:</strong></th>
            <th><strong>Distribuido antes de las 18.00 el:&nbsp;</strong></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Lunes</td>
            <td>Martes</td>
        </tr>
        <tr>
            <td>Martes</td>
            <td>Miércoles</td>
        </tr>
        <tr>
            <td>Miércoles</td>
            <td>Jueves</td>
        </tr>
        <tr>
            <td>Jueves</td>
            <td>Viernes</td>
        </tr>
        <tr>
            <td>Viernes</td>
            <td>Sábado</td>
        </tr>
        <tr>
            <td>Sábado</td>
            <td>Martes</td>
        </tr>
        <tr>
            <td>Domingo</td>
            <td>Martes</td>
        </tr>
        </tbody>
    </table>
    <p>&nbsp;</p>
    <p><strong>Envío internacional y plazos de entrega</strong></p>
    <p>Los gastos de envío de pedidos internacionales varían según el destino. El peso máximo por paquete es de 30kg. En el caso de que se sobrepase el peso máximo, se aplicarán gastos de envío extra. Todos los envíos internacionales se realizan mediante correo certificado, incluyendo seguro y número de seguimiento por Post NL.</p>
    <p>&nbsp;</p>
    <table style="margin-left: auto; margin-right: auto;" border="2">
        <thead>
        <tr>
            <th scope="row"><strong>Destino</strong></th>
            <th><strong>Gastos de envío en euro (€)</strong></th>
            <th><strong>Plazo de entrega</strong></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Bélgica</td>
            <td>10.00</td>
            <td>1-2</td>
        </tr>
        <tr>
            <td>Bulgaria</td>
            <td>28.00</td>
            <td>5</td>
        </tr>
        <tr>
            <td>Dinamarca</td>
            <td>18.50</td>
            <td>3-4</td>
        </tr>
        <tr>
            <td>Alemania</td>
            <td>10.00</td>
            <td>1-2</td>
        </tr>
        <tr>
            <td>Estonia</td>
            <td>29.00</td>
            <td>4-5</td>
        </tr>
        <tr>
            <td>Finlandia</td>
            <td>23.50</td>
            <td>4-5</td>
        </tr>
        <tr>
            <td>Reino Unido</td>
            <td>14.00</td>
            <td>2-3</td>
        </tr>
        <tr>
            <td>Hungría</td>
            <td>25.00</td>
            <td>3-5</td>
        </tr>
        <tr>
            <td>Irlanda</td>
            <td>24.00</td>
            <td>3-4</td>
        </tr>
        <tr>
            <td>Italia</td>
            <td>18.50</td>
            <td>3-4</td>
        </tr>
        <tr>
            <td>Letonia</td>
            <td>29.00</td>
            <td>4-5</td>
        </tr>
        <tr>
            <td>Lituania</td>
            <td>29.00</td>
            <td>4-5</td>
        </tr>
        <tr>
            <td>Luxemburgo</td>
            <td>14.00</td>
            <td>2</td>
        </tr>
        <tr>
            <td>Austria</td>
            <td>18.50</td>
            <td>2-4</td>
        </tr>
        <tr>
            <td>Polonia</td>
            <td>25.00</td>
            <td>3-4</td>
        </tr>
        <tr>
            <td>Portugal</td>
            <td>23.00</td>
            <td>3-5</td>
        </tr>
        <tr>
            <td>Eslovenia</td>
            <td>25.00</td>
            <td>4-5</td>
        </tr>
        <tr>
            <td>Eslovaquia</td>
            <td>25.00</td>
            <td>3-5</td>
        </tr>
        <tr>
            <td>España</td>
            <td>23.00</td>
            <td>3-5</td>
        </tr>
        <tr>
            <td>República Checa</td>
            <td>25.00</td>
            <td>3-5</td>
        </tr>
        <tr>
            <td>Suecia</td>
            <td>24.00</td>
            <td>2-4</td>
        </tr>
        <tr>
            <td>Noruega</td>
            <td>28.00</td>
            <td>2-4</td>
        </tr>
        <tr>
            <td>Suiza</td>
            <td>28.00</td>
            <td>2-3</td>
        </tr>
        <tr>
            <td>Resto de Europa</td>
            <td>28.00</td>
            <td>3-5</td>
        </tr>
        </tbody>
    </table>
    &nbsp;
    <p>* Para otros destinos internacionales: </strong>por favor contacte con nosotros para pedir una cotización.</p>
</div>
<div id="payment">
    <h2><span style="color: #000000;"><a style="color: #000000;" href="https://www.mimosacompany.com/payment-methods">Formas de pago aceptadas</a></span></h2>
    <h4>¿Cómo puedo pagar mi pedido?</h4>
    <p>Puede hacer su pedido mediante diversos métodos de pago. Actualmente ofrecemos los siguientes:</p>
    <ul>
        <li><strong>Ideal</strong></li>
        <li><strong>Sofort</strong></li>
        <li><strong>GiroPay</strong></li>
        <li><strong>Bancontant / Mister Cash</strong></li>
    </ul>
</div>
<div id="warranty">
    <h2><span style="color: #000000;"><a style="color: #000000;" href="https://www.mimosacompany.com/warranty-complaints">Garantía y reclamaciones</a></span></h2>
    <h4>Garantía</h4>
    <p>Nos preocupamos de nuestros productos, y hacemos todo lo posible por entregarlos en las mejores condiciones. Sin embargo, si por algún motivo un producto se rompe durante el transporte, o pasa alguna otra cosa que le da derecho a realizar una reclamación, deberá por ley informarnos de ello en el plazo máximo de dos meses tras el descubrimiento del problema. Si la deficiencia está cubierta por la garantía, nos encargaremos de realizar el reemplazo sin coste para usted.</p>
    <h4>Proceso de reclamación</h4>
    <p>Le aconsejamos que envíe su queja por correo electrónico a: <strong>info@mimosacompany.com</strong>. Si esto no soluciona su problema, es posible notificar la disputa para su conciliación a <strong>Stichting WebwinkelKeur</strong>. Desde el 15 de febrero de 2016, los consumidores en la UE pueden también registrar sus quejas usando la <strong>plataforma ODR de la Comisión Europea</strong>. Esta plataforma ODR puede encontrarse en <strong>http://ec.europa.eu/odr</strong>. Si su reclamación todavía no se ha realizado en ningún otro lugar, podrá presentarla a través de la plataforma de la Unión Europea.</p>
</div>
<div id="returns">
    <h2><a href="https://www.mimosacompany.com/returns"><span style="color: #000000;">Devoluciones</span></a></h2>
    <h4>Periodo de reflexión / Devoluciones</h4>
    <p>De forma ocasional, puede que quiera devolver un pedido. Puede que el producto no satisfaga sus necesidades, o alguna otra razón por la que no quiere ya la mercancía. Le pedimos por favor que tenga en cuenta las siguientes normas relativas a la devolución de pedidos realizados a The Mimosa Company:</p>
    <ol>
        <li>Los productos alimentarios que compre en esta tienda online tienen una vida de anaquel limitada, y por tanto, no pueden ser devueltos. Por ende, no se aplica el derecho a devolución. Tras la realización de un pago de forma efectiva, la venta es ya un hecho consumado.</li>
        <li>Para los productos que no están bajo la categoría alimentaria, puede hacer uso del derecho de desistimiento. Para estos productos, tiene el derecho a cancelar el pedido durante los 14 días siguientes a la recepción del mismo, sin necesidad de dar ningún motivo. Tras la cancelación, tendrá de nuevo otros 14 días para devolver el producto.</li>
    </ol>
    <p>Cuando devuelva un pedido completo recibirá el reembolso total de la compra, incluyendo los gastos de envío. Solo los gastos de la devolución de su hogar a la tienda online corren por su cuenta. Estos costes son de aproximadamente €6,95 por paquete para envíos dentro de los Países Bajos. Para saber las tarifas concretas, por favor, consulte la página web de su transportista o empresa de servicio de paquetería que usted prefiera.</p>
    <p>Si solo devuelve parte del pedido, recibirá un reembolso equivalente al valor de los artículos devueltos excluyendo los gastos de envío. Si ejercita su derecho de desistimiento, deberá devolver a The Mimosa Company, los productos incluyendo todos sus accesorios y, en la medida de lo razonable, en su estado original y con su embalaje. Para hacer uso de este derecho debe rellenar el <a title="Formulario de disestimiento" href="{{media url=&quot;documents/Withdrawal_form_The_Mimosa_Company_English.pdf&quot;}}" target="_blank" rel="noopener"><strong>formulario normalizado de desistimiento</strong> </a>y enviárnoslo a <strong>info@mimosacompany.com</strong>. Le reembolsaremos entonces la cantidad de la compra en los 14 días siguientes al registro de su devolución, siempre y cuando el producto llegue en las condiciones adecuadas.</p>
    <p>Si un producto está dañado, o el paquete fue deteriorado más de lo necesario para probar el producto, calcularemos una reducción en el valor del producto, que correrá a su cargo. Por esta razón, tenga cuidado con el artículo y asegúrese de que, en caso de que quiera devolverlo, el producto vaya perfectamente embalado.</p>
    <p><strong>¡He proporcionado una dirección de entrega incorrecta!</strong></p>
    <p>¿Nos ha proporcionado accidentalmente una dirección de entrega incorrecta? Por favor, contacte con nosotros lo antes posible. Trataremos de cambiar el pedido inmediatamente.</p>
</div>