<p><img src="{{media url=&quot;wysiwyg/BLOGS_HEADER_5.jpg&quot;}}" alt="Mimosa hostilis" width="1200"></p>
<p>Het looien van huiden met plantaardige methoden is een milieuvriendelijkere, creatieve en artisanale optie. We leggen je uit hoe je huiden kan looien met de Mimosa hostilis.</p>
<h2>Inhoud</h2>
<ol>
    <li><a href="#the"> De chemie en traditie achter het looien met Mimosa hostilis </a></li>
    <li><a href="#how"> Hoe gebeurt de extractie van tannines uit de Mimosa hostilis? </a></li>
    <li><a href="#step"> Stap voor stap: plantaardig looien met de Mimosa hostilis </a></li>
    <li><a href="#one"> Een laatste tip: hoe de vacht behouden met de Mimosa hostilis </a></li>
</ol>
<p>&nbsp;</p>
<p>Het extract van de <em>Mimosa hostilis </em>heeft ideale eigenschappen om huiden te looien. Dat weten enkele ambachtslui, handelaars, onderzoekers en kunstenaars, maar de beschikbare informatie is beperkt. Om dit gebruik te verkennen, hebben we de taak op ons genomen om experts te interviewen, bronnen te raadplegen en deze techniek met u te delen. Wilt u het proberen?</p>
<p>Zoals gebeurt met &nbsp;het verven van textiel, kan het gebruik van de <em>Mimosa tenuiflora </em>(<em>syn.</em>) een meer milieuvriendelijke techniek zijn en daarom een alternatief voor technieken die gebruik maken van chroom, aluminium, zirkonium en andere chemische stoffen, zoals zwavelzuur.<span style="font-size: 8pt;"><a href="#_ftn1" name="_ftnref1">1</a> </span>De techniek waarbij gebruik gemaakt wordt van planten staat bekend als “plantaardig looien” terwijl de techniek waarbij gebruik gemaakt wordt van de vermelde chemische stoffen, bekend staat als “mineraal looien”. De verschillen tussen de technieken hebben hun voors en tegens.</p>
<p>Op de markt wordt het plantaardig looien van huiden gewaardeerd omdat de huiden zwaarder en dikker zijn<a href="#_ftn2" name="_ftnref2"><sup>2</sup></a>, waardoor ze meer waard zijn, omdat ze op basis van gewicht verkocht worden<a href="#_ftn3" name="_ftnref3"><sup>3</sup></a> <a href="#_ftn4" name="_ftnref4"><sup>4</sup></a>, leggen de experts van het Centro de Innovación Aplicada en Tecnologías Competitivas (CIATEC – Centrum voor Toegepaste Innovatie in Concurrerende Technologieën) ons uit, een instituut gelegen in de stad León, in het centrum van Mexico, die bekend staat om zijn grote schoen- en lederwarenindustrie. &nbsp;</p>
<p>De huiden die geproduceerd worden met de plantaardige techniek zijn zeer geschikt om gravures in te maken; ze zijn er makkelijk in te maken en blijven lang mooi,, iets wat niet het geval is bij het mineraal looien<a href="#_ftn5" name="_ftnref5"><sup>5</sup></a>, legt Yolanda Nieto Urroz, Technisch Consultant in Looiprocessen in het Departement Technologieoverdracht van CIATEC ons uit. Op zoek naar ideeën over hoe u deze eigenschap in uw voordeel kan gebruiken? Deze eigenschap is nuttig om handtekeningen of zegels in het leer te drukken.</p>
<p>Iets wat u niet mag vergeten is dat een nadeel van de techniek met planten zich voordoet bij blootstelling aan het licht. Mettertijd oxideert leder dat plantaardig gelooid is en kan het van kleur veranderen en donker worden.<a href="#_ftn6" name="_ftnref6"><sup>6</sup></a></p>
<p id="the">&nbsp;</p>
<h2>De chemie en traditie achter het looien met Mimosa hostilis</h2>
<p>Kunnen huiden gelooid worden met <em>Mimosa tenuiflora</em>? Het eenvoudige antwoord is <em>ja,</em> maar daar zitten de tannines achter, essentiële stoffen in het looiproces en de samenstelling van extracten van <em>Mimosa hostilis</em> en de interactie ervan met het collageen van de huid. &nbsp;</p>
<p>Deze interactie is bekend sinds de oudheid, toen de beschavingen vaststelden dat de huid resistent werd bij blootstelling aan bepaalde schorssoorten en dat dit verrotting voorkwam.<a href="#_ftn7" name="_ftnref7">[<span style="font-size: 8pt;">7</span></a></p>
<p>Er zijn al vanaf het jaar 1000 v. Chr. antecedenten aangetroffen van het looien.<span style="font-size: 8pt;"><a href="#_ftn8" name="_ftnref8">8</a> </span>In het oude Fenicië werden fijn behandelde huiden gebruikt en de precolumbiaanse Noord-Amerikaanse stammen looiden buffelhuiden, waarbij ze gebruik maakten van de techniek met planten die overgebracht werd naar Europa. Al deze technieken komen overeen in het feit dat ze gebruik maken van de adstringerende eigenschap van de extracten. Hoewel het aan het einde van de 18de eeuw was dat in Frankrijk de chemische stoffen ontdekt werden waarmee de huid gelooid wordt: de tannines.<span style="font-size: 8pt;"><a href="#_ftn9" name="_ftnref9">9</a></span></p>
<p>Laten we het over chemie hebben. Tannines zijn zeer adstringerende zuren, die het resultaat zijn van de combinatie tussen een fenol en een suiker<span style="font-size: 8pt;"><a href="#_ftn10" name="_ftnref10">10.</a></span> Een tannine is een polifunctionele organische samenstelling, die gevormd wordt door koolstof, waterstof en zuurstof, beschreef Benjamín Aguilar Ruíz, Technisch Consultant Gespecialiseerd in Natte Looiprocessen van het Departement voor Technologische Oplossingen van het CIATEC. De chemische samenstelling van de grote meerderheid van de plantaardige extracten bevat tannines.<span style="font-size: 8pt;"><a href="#_ftn11" name="_ftnref11">11</a></span></p>
<p>De interactie van tannines met het collageen is wat ons het flexibele, resistente en duurzame resultaat geeft dat kenmerkend is voor leer. Collageen is een eiwit dat aangetroffen wordt in de huid van dieren en dat men wil behouden in het looiproces. Tannines kunnen binden met collageen. Deze verbinding maakt het mogelijk collageen te stabiliseren, zodat het niet afgebroken wordt. Als een materiaal tannines bevat, dan kan het collageen altijd stabiliseren<a href="#_ftn12" name="_ftnref12"><sup>12</sup></a>, legt onderzoeker Nieto uit.</p>
<p>Looimiddelen zorgen ervoor dat huiden getransformeerd kunnen worden in leer en de tannines vervullen deze functie. &nbsp;</p>
<p>Tannines hebben een bittere smaak<span style="font-size: 8pt;"><a href="#_ftn13" name="_ftnref13">13</a></span> en kunnen aanwezig zijn in elk deel van de plant, de stengel, de schors, de wortel, de bladeren en zelfs in het fruit en de zaden.<a href="#_ftn14" name="_ftnref14"><sup>14</sup></a> <a href="#_ftn15" name="_ftnref15"><sup>15</sup></a> <a href="#_ftn16" name="_ftnref16"><sup>16</sup></a> <a href="#_ftn17" name="_ftnref17"><sup>17</sup></a> Hoewel elke plant een verschillende, bijzondere samenstelling heeft,<a href="#_ftn18" name="_ftnref18"><sup>18</sup></a> kan hij als looimiddel gebruikt worden als hij tannines bevat.<a href="#_ftn19" name="_ftnref19"><sup>19</sup></a> Dat wil zeggen, wanneer een plant tannines bevat, kunnen deze geëxtraheerd worden en de reactie uitlokken (looien) die we nodig hebben voor het looiproces.<a href="#_ftn20" name="_ftnref20"><sup>20</sup></a></p>
<p>Hoewel er geen minimumconcentratie is voor de noodzakelijke tannines,<a href="#_ftn21" name="_ftnref21"><sup>21</sup></a> <a href="#_ftn22" name="_ftnref22"><sup>22</sup></a> dient een plant idealiter te beschikken over de hoogst mogelijke concentratie zodat het de moeite waard is om te extraheren en om duurzaam te zijn.<a href="#_ftn23" name="_ftnref23"><sup>23</sup></a> De soorten met de meeste tannines zijn het meest rendabel. Indien een plant slechts over een kleine hoeveelheid beschikt, is hij minder kostenefficiënt <a href="#_ftn24" name="_ftnref24"><sup>24</sup></a>, leggen de onderzoekers van het CIATEC ons uit. &nbsp;</p>
<p>Desondanks kunnen planten met een kleinere hoeveelheid tannines ook gebruikt worden om te looien, het volstaat om ze in een grotere concentratie te gebruiken en met een grotere hoeveelheid product.<a href="#_ftn25" name="_ftnref25"><sup>25</sup></a> Ook kunnen ze gecombineerd worden met een andere looistof om het effect ervan te vergroten.<a href="#_ftn26" name="_ftnref26"><sup>26</sup></a> <a href="#_ftn27" name="_ftnref27"><sup>27</sup></a></p>
<p>Als een plant over minder dan 5% tannines beschikt, is de extractie niet de moeite waard.<a href="#_ftn28" name="_ftnref28"><sup>28</sup></a> <a href="#_ftn29" name="_ftnref29"><sup>29</sup></a> Hierover zijn José León Montoya Valadez, Technisch Consultant in Productieprocessen en José Martín Calvillo Mares, Technisch Consultant gericht op de Droge Afwerking van Leer van het CIATEC het eens.</p>
<p>Een ideaal gehalte aan tannines voor een rendabele extractie zou rond 70% zijn.<a href="#_ftn30" name="_ftnref30"><sup>30</sup></a> De meeste commerciële producten waarmee plantaardig gelooid wordt, zoals extract van quebrachos (bomen van het geslacht <em>Schinopsis</em>)<a href="#_ftn31" name="_ftnref31"><span style="font-size: 8pt;">31</span></a>, beschikken over een hoeveelheid tannines van tussen 70 en 80%.<a href="#_ftn32" name="_ftnref32"><sup>32</sup></a></p>
<p><strong>&nbsp;</strong>Er bestaan studies waarin de effecten van extracten van het blad en de stengel van de <em>Mimosa tenuiflora</em> <em>(Willd.) Poir </em>geëvalueerd worden. De resultaten toonden aan dat het extract in totaal 30,13 mg gallische tannines bevat per gram extract. In de schors werd een totaal aangetroffen van 138,85 gallische tannines voor elke gram extract.<a href="#_ftn33" name="_ftnref33"><sup>33</sup></a> Andere studies toonden het bestaan aan van bijna 70% gecondenseerde tannines in het extract van de schors van <em>Mimosa tenuiflora</em>.<a href="#_ftn34" name="_ftnref34"><sup>34</sup></a></p>
<p>Het is om die reden dat de schors van de tepezcohuite, de Mexicaanse naam van de <em>Mimosa hostilis</em> plant, ideaal is om plantaardig te looien.</p>
<p id="how">&nbsp;</p>
<h2>Hoe gebeurt de extractie van tannines uit de Mimosa hostilis?</h2>
<p>Nu we het belang begrijpen van tannines voor het looien, is de extractie uit de schors de eerste stap. Deze dient van de stam gescheiden te worden zonder het hout te beschadigen. Idealiter dient dit op een gematigde wijze uitgevoerd te worden, met respect voor de regeneratietijd van de schors.<a href="#_ftn35" name="_ftnref35"><sup>35</sup></a> Vervolgens wordt deze geplet of fijngemaakt in zo klein mogelijke stukjes<a href="#_ftn36" name="_ftnref36"><sup>36</sup></a>, legt María Alejandra Rivera Trasgallo, Adviseur-Onderzoeker in het domein Milieu van het CIATEC ons uit.<a href="#_ftn37" name="_ftnref37"><sup>37</sup></a></p>
<p>Het extractieproces voor tannines is gelijkaardig aan een infusie:<a href="#_ftn38" name="_ftnref38"><sup>38</sup></a> <a href="#_ftn39" name="_ftnref39"><sup>39</sup></a></p>
<ol>
    <li>In een kom wordt warm water gegoten en worden kleine stukken schors toegevoegd om sneller een reactie te krijgen. &nbsp;</li>
    <li>Er moet voortdurend geroerd worden.<a href="#_ftn40" name="_ftnref40"><sup>40</sup></a> De kleurverandering van het water geeft aan dat het proces op de goede weg is.<a href="#_ftn41" name="_ftnref41"><sup>41</sup></a></li>
    <li>Filteren. Deze vloeistof bevat de tannines al.<a href="#_ftn42" name="_ftnref42"><sup>42</sup></a></li>
    <li>De infusie van looimaterialen op hoge temperatuur laten drogen, dit geeft een poeder als resultaat.<a href="#_ftn43" name="_ftnref43"><sup>43</sup></a></li>
</ol>
<p id="step">&nbsp;</p>
<h2>Stap voor stap: plantaardig looien met de Mimosa hostilis</h2>
<p><strong>1. Weken</strong></p>
<p>Wanneer een dier gevild is, wordt de huid gewoonlijk bewaard met zout om ontbinding te voorkomen.<a href="#_ftn44" name="_ftnref44"><sup>44</sup></a> Vlak na het villen, bevat de huid tussen 60 en 70% water. Bij het overbrengen naar de plaats waar de huid gelooid wordt, wordt de huid beetje bij beetje gedehydrateerd.<a href="#_ftn45" name="_ftnref45"><sup>45</sup></a></p>
<p>Om de huid opnieuw te hydrateren, wordt deze in een bad geplaatst waarin hij uitgestrekt wordt en wordt een waterbad toegevoegd. De hoeveelheid water dient 100% te zijn ten opzichte van het gewicht van de huid.<a href="#_ftn46" name="_ftnref46"><sup>46</sup></a> Als een huid bijvoorbeeld 30 kilo weegt, dan dient deze in ongeveer 30 liter geweekt te worden. <a href="#_ftn47" name="_ftnref47"><sup>47</sup></a></p>
<p>Als de huid in zout bewaard werd, dient deze gedurende 48 uur geweekt te worden. Indien de huid niet de gewenste flexibiliteit heeft, kan hij nog eens 24 uur geweekt worden. Het water dient voortdurend vervangen te worden tot het schoon blijft. De net gevilde huid dient zes uur schoongemaakt te worden en vrij van vuil, bloed, vlees en vet gemaakt te worden voor het weken.<a href="#_ftn48" name="_ftnref48"><sup>48</sup></a></p>
<p>Aan het einde van het weken dient de huid flexibel te zijn en gewassen te worden tot het water schoon blijft.<a href="#_ftn49" name="_ftnref49"><sup>49</sup></a> Zodra het proces ten einde is, wordt het gebruikte water verwijderd.<a href="#_ftn50" name="_ftnref50"><sup>50</sup></a></p>
<p><strong>2. Kalken</strong></p>
<p>In de fase van het kalken of ontharen, worden de huiden uitgestrekt en in een ander bad gelegd met natriumsulfide en kalk tot ze volledig ondergedompeld zijn<a href="#_ftn51" name="_ftnref51"><sup>51</sup></a> <a href="#_ftn52" name="_ftnref52"><sup>52</sup></a> gedurende 72 uur.<a href="#_ftn53" name="_ftnref53"><sup>53</sup></a> De kalk opent de huidvezels zodat ze later de looistoffen kunnen opnemen.<a href="#_ftn54" name="_ftnref54"><sup>54</sup></a></p>
<p>Na een tijdje valt het haar vanzelf uit en blijft alleen de huid over<a href="#_ftn55" name="_ftnref55"><sup>55</sup></a> en verdrievoudigt de dikte.<a href="#_ftn56" name="_ftnref56"><sup>56</sup></a> Het water met haar moet verwijderd worden na het proces.<a href="#_ftn57" name="_ftnref57"><sup>57</sup></a></p>
<p><strong>3. Ontvlezen</strong></p>
<p>Bij het ontvlezen wordt de huid met het buitenste gedeelte naar beneden gelegd. Vervolgens wordt met een mes het vlees verwijderd tot het de gewenste dikte heeft. Het mes kan ook helpen om het resterende haar te verwijderen. In deze fase is er veel water nodig om de huid te reinigen.<a href="#_ftn58" name="_ftnref58"><sup>58</sup></a></p>
<p><strong>4. </strong><strong>Ontkalken</strong></p>
<p>Ontkalken houdt in dat de kalk die overgebleven is na het kalkproces verwijderd wordt.<a href="#_ftn59" name="_ftnref59"><sup>59</sup></a> Zodra de huiden geen schubben of haar meer hebben, worden ze gedurende 72 uur in een ander bad gelegd, tot er geen kalkresten meer zijn. Terwijl ze geweekt worden, dienen de huiden er om de 12 uur uitgehaald , geschrobd en geschraapt te worden. Voor elke wasbeurt dient het water vervangen te worden. <a href="#_ftn60" name="_ftnref60"><sup>60</sup></a></p>
<p>Ter ondersteuning voor dit proces kan gebruik gemaakt worden van ammoniumsulfaat, natriumbisulfiet of commerciële ontkalkingsmiddelen.<a href="#_ftn61" name="_ftnref61"><sup>61</sup></a></p>
<p><strong>5. Pikkelen</strong></p>
<p>Gedurende dit proces wordt de pH van de huid gewijzigd. Voor een beter effect van de looimaterialen, is het belangrijk om ervoor te zorgen dat de huid een pH van 5 heeft.<a href="#_ftn62" name="_ftnref62"><sup>62</sup></a> Een manier om dat te bereiken is met mierenzuur.<a href="#_ftn63" name="_ftnref63"><sup>63</sup></a></p>
<p><strong>6. Looien</strong></p>
<p><strong>&nbsp;</strong>Na deze stap is het leer klaar. Er wordt schoon water aangebracht met een minimale hoeveelheid schors, die kleur geeft aan de eerste laag van de huid. De huid wordt met de buitenkant naar boven in een ander verfbad met schors van de <em>Mimosa tenuiflora</em> (syn. <em>Mimosa hostilis</em>) gelegd.<a href="#_ftn64" name="_ftnref64"><sup>64</sup></a></p>
<p>Dit dient gedurende 72 uur driemaal per dag geroerd worden. Wanneer de hoofdzijde van de huid gekleurd is, wordt de positie gewijzigd en wordt de binnenzijde naar boven gelegd. Ook wordt er een grote lading schors toegevoegd.<a href="#_ftn65" name="_ftnref65"><sup>65</sup></a></p>
<p>Men kan zien dat de tannines goed doorgedrongen zijn in de huid wanneer deze de kleur krijgt van het plantaardige looimiddel, in dit geval, de kleur van de <em>Mimosa hostilis</em><a href="#_ftn66" name="_ftnref66"><sup>66</sup></a></p>
<p>Nadien wordt een laatste wasbeurt uitgevoerd, of de huid wordt geweekt in water met zeep gedurende drie uur. Na deze laatste wasbeurt is het leer klaar. <a href="#_ftn67" name="_ftnref67"><sup>67</sup></a></p>
<p id="one">&nbsp;</p>
<h2>Een laatste tip: hoe de vacht behouden met de Mimosa hostilis</h2>
<p><strong>&nbsp;</strong>Als u de vacht wenst te behouden, is het looiproces hetzelfde, maar worden de stappen van het kalken (stap 2) en die van het ontkalken (stap 4) gewoon overgeslagen, aangezien er geen kalk gebruikt wordt. Na het weken wordt er ontvleesd, wordt de pH gecontroleerd en wordt overgegaan tot de stap van het looien, met behoud van de vacht. <a href="#_ftn68" name="_ftnref68"><sup>68</sup></a> <a href="#_ftn69" name="_ftnref69"><sup>69</sup></a></p>
<p>Optioneel kan de vacht voorbereid worden tijdens de stap van het weken. Gebruik een beetje mierenzuur om de vacht te verstevigen met de huid en te voorkomen dat deze uitvalt gedurende het proces.<a href="#_ftn70" name="_ftnref70"><sup>70</sup></a></p>
<p>&nbsp;</p>
<h4 style="text-align: center;">Klaar om het te proberen? &nbsp;Lees hier de ervaringen van mensen die dit proces gevolgd hebben.</h4>
<hr>
<div style="border: 1px solid #ccc; padding: 20px 27px; margin-bottom: 38px;">
<h4 style="margin-top: 11px; margin-bottom: 14px;">Met dank aan</h4>
<ul>
    <li>Centro de Innovación Aplicada en Tecnologías Competitivas (CIATEC), onderdeel van het Red de Centros Públicos del Consejo Nacional de Ciencia y Tecnología (CONACYT) van Mexico.</li>
    <li>Benjamín Aguilar Ruíz, Technisch Consultant Gespecialiseerd in Natte Looiprocessen van het Departement voor Technologische Oplossingen van het CIATEC.</li>
    <li>José León Montoya Valadez, Technisch Consultant in Productieprocessen van het Departement voor Technologische Oplossingen van het CIATEC.</li>
    <li>José Martín Calvillo Mares, Technisch Consultant gericht op de Droge Afwerking van Leer van het Departement voor Technologische Oplossingen van het CIATEC.</li>
    <li>María Alejandra Rivera Trasgallo, Adviseur-Onderzoeker in het domein Milieu van het CIATEC van de Directie voor Technologische Oplossingen van het CIATEC.</li>
    <li>Yolanda Nieto Urroz, Technisch Consultant in Looiprocessen in het Departement Technologieoverdracht van het CIATEC.</li>
</ul>
</div>
<div style="border: 1px solid #ccc; padding: 11px 27px;">
<h4 style="margin-bottom: 16px;">Referenties</h4>
<p><a href="#_ftnref1" name="_ftn1"> 1. </a> Duque, O. (2007).<span style="color: #333333;"> <a style="color: #333333;" href="http://lasallista.edu.co/fxcul/media/pdf/RevistaLimpia/vol2n2/PL_V2N2_47-56_cuero.pdf">http://lasallista.edu.co/fxcul/media/pdf/RevistaLimpia/vol2n2/PL_V2N2_47-56_cuero.pdf</a></span></p>
<p><a href="#_ftnref2" name="_ftn2"> 2. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref3" name="_ftn3"> 3. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref4" name="_ftn4"> 4. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref5" name="_ftn5"> 5. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref6" name="_ftn6"> 6. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref7" name="_ftn7"> 7. </a> Gómez, E. (2004). Comparación del porcentaje de extracto tánico de la corteza y de la madera de encino (Quercus tristis Liebm) proveniente de un bosque natural.&nbsp; Universidad de San Carlos de Guatemala. Facultad de Ingeniería. Escuela de Ingeniería Química. Guatemala, noviembre 2004.</p>
<p><a href="#_ftnref8" name="_ftn8"> 8. </a> Gómez, E. (2004).</p>
<p><a href="#_ftnref9" name="_ftn9"> 9. </a> Gómez, E. (2004).</p>
<p><a href="#_ftnref10" name="_ftn10"> 10. </a> Gómez, E. (2004).</p>
<p><a href="#_ftnref11" name="_ftn11"> 11. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref12" name="_ftn12"> 12. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref13" name="_ftn13">  st ont-size: 8pt;">13.</span></a> Gómez, E. (2007).</p>
<p><a href="#_ftnref14" name="_ftn14"> 14. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref15" name="_ftn15"> 15. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref16" name="_ftn16"> 16. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref17" name="_ftn17"> 17. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref18" name="_ftn18"> 18. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref19" name="_ftn19"> 19. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref20" name="_ftn20"> 20. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref21" name="_ftn21"> 21. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref22" name="_ftn22"> 22. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref23" name="_ftn23"> 23. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref24" name="_ftn24"> 24. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref25" name="_ftn25"> 25. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref26" name="_ftn26"> 26. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref27" name="_ftn27"> 27. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref28" name="_ftn28"> 28. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref29" name="_ftn29"> 29. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref30" name="_ftn30"> 30. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref31" name="_ftn31"> 31. </a> Barberis, I. M. et al, (2012). Biología de especies australes: Schinopsis balansae Engl. (Anarcadiacea). <em>Kurtziana</em></p>
<p><a href="#_ftnref32" name="_ftn32"> 32. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref33" name="_ftn33"> 33. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://www.scielo.br/scielo.php?script=sci_arttext&amp;pid=S1984-29612011000200011&amp;lng=en&amp;nrm=iso&amp;tlng=en">Oliveira, L. M.; Bevilaqua, C. M. (2011). “Effect of six tropical tanniferous plant extracts on larval exsheathment of Haemonchus contortus.” Rev Bras Parasitol Vet 20(2): 155-160.</a></span></p>
<p><a href="#_ftnref34" name="_ftn34"> 34. </a> <span style="color: #333333;">Anton, R., Jiang, Y. (1993). “Pharmacognosy of Mimosa tenuiflora (Willd.) Poiret.” J Ethnopharmacol 38(2-3): 153-157</span></p>
<p><a href="#_ftnref35" name="_ftn35"> 35. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref36" name="_ftn36"> 36. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref37" name="_ftn37"> 37. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref38" name="_ftn38"> 38. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref39" name="_ftn39"> 39. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref40" name="_ftn40"> 40. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref41" name="_ftn41"> 41. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref42" name="_ftn42"> 42. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref43" name="_ftn43"> 43. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref44" name="_ftn44"> 44. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref45" name="_ftn45"> 45. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref46" name="_ftn46"> 46. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref47" name="_ftn47"> 47. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref48" name="_ftn48"> 48. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref49" name="_ftn49"> 49. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref50" name="_ftn50"> 50. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref51" name="_ftn51"> 51. </a><span style="color: #333333;"> <a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref52" name="_ftn52"> 52. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref53" name="_ftn53"> 53. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref54" name="_ftn54"> 54. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref55" name="_ftn55"> 55. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref56" name="_ftn56"> 56. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref57" name="_ftn57"> 57. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref58" name="_ftn58"> 58. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref59" name="_ftn59"> 59. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref60" name="_ftn60"> 60. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref61" name="_ftn61"> 61. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref62" name="_ftn62"> 62. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref63" name="_ftn63"> 63. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref64" name="_ftn64"> 64. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref65" name="_ftn65"> 65. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref66" name="_ftn66"> 66. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref67" name="_ftn67"> 67. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref68" name="_ftn68"> 68. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref69" name="_ftn69"> 69. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref70" name="_ftn70"> 70. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
</div>