<p><img src="{{media url="wysiwyg/BLOGS_HEADER_5.jpg"}}" alt="Mimosa hostilis " width="1200"></p>
<p>Leather tanning with vegetable methods is a more environmentally friendly, creative, and handmade option. We explain how to tan leather with Mimosa hostilis.</p>
<h2>Content</h2>
<ol>
    <li><a href="#the"> The chemistry and tradition behind Mimosa hostilis tanning </a></li>
    <li><a href="#how"> How to extract the tannins from Mimosa hostilis? </a></li>
    <li><a href="#step"> Step by step: Tanning the vegetable with Mimosa hostilis </a></li>
    <li><a href="#one"> One last tip: How to preserve the fur with Mimosa hostilis </a></li>
</ol>
<p>&nbsp;</p>
<p><em>Mimosa hostilis</em> extract has ideal properties for tanning leather. This is known by some craftsmen, traders, researchers and artists, however, the information available is limited. To explore this use further, we took the time to interview experts, consult sources and share this technique with you. Would you try it?</p>
<p>As with textile dyeing&nbsp;, using <em>Mimosa tenuiflora (syn.)</em> can be a more environmentally friendly technique and therefore an alternative to techniques involving chrome, aluminium, zirconium, and other chemicals such as sulphuric <span style="font-size: 8pt;">acid<a href="#_ftn1" name="_ftnref1">1</a>.</span> The technique in which plant derivatives are used is known as "vegetable tanning" while that in which the above-mentioned chemicals are used is known as "mineral tanning". The differences between one technique and another have pros and cons.</p>
<p>&nbsp;In the market, vegetable tanning is appreciated because it produces heavier and thicker leather<a href="#_ftn2" name="_ftnref2"><sup>2</sup></a>, which is better priced, as it sells by weight<a href="#_ftn3" name="_ftnref3"><sup>3</sup></a> <a href="#_ftn4" name="_ftnref4"><sup>4</sup></a>, explained experts from the Centre for Applied Innovation in Competitive Technologies (CIATEC), an institution located in the city of Leon, central Mexico, recognised for its large industry of footwear and other leather products.</p>
<p>The leathers resulting from the vegetable technique are very suitable for engraving, they are easily accepted and preserved, something that does not happen with mineral tanning<a href="#_ftn5" name="_ftnref5"><sup>5</sup></a>, explained Yolanda Nieto Urroz, Technical Consultant in Tanning Processes at the Technology Transfer Department of CIATEC. Do you want ideas on how to use this quality to your advantage? This feature is useful to print signatures or stamps on the leathers.</p>
<p>One thing you should not forget is that a disadvantage of the plant technique occurs with exposure to light. Over time, vegetable-tanned leather oxidises and may change colour and darken.<a href="#_ftn6" name="_ftnref6"><sup>6</sup></a></p>
<p id="the">&nbsp;</p>
<h2>The chemistry and tradition behind Mimosa hostilis tanning</h2>
<p>Can you tan leather with <em>Mimosa tenuiflora</em>? The simple answer is <em>yes</em>, but behind it are the tannins, key substances in the tanning process and the composition of the <em>Mimosa hostilis</em> extracts and their interaction with the skin collagen.</p>
<p>This interaction has been known since ancient times, when civilisations observed that skin that came into contact with certain bark became resistant and prevented rot<span style="font-size: 8pt;"><a href="#_ftn7" name="_ftnref7">7</a>.</span></p>
<p>A history of tanning has been found since 1000 <span style="font-size: 8pt;">BC<a href="#_ftn8" name="_ftnref8">8</a>.</span> in the ancient Phoenicia, finely treated hides were used and the pre-Columbian American tribes tanned buffalo skin, dominating the technique with plants that transcended Europe. All those techniques coincide in handling the astringent property of the extracts. Although it was until the end of the 18th century when the chemicals that tanned the skin were discovered in France: tannins<span style="font-size: 8pt;"><a href="#_ftn9" name="_ftnref9">9</a></span>.</p>
<p>Let's talk about chemistry. Tannins are very astringent acids and they are the result of the combination of a phenol and a sugar<span style="font-size: 8pt;"><a href="#_ftn10" name="_ftnref10">10</a></span>. Tannin is a polyfunctional organic compound formed by carbon, hydrogen and oxygen, described Benjamín Aguilar Ruíz, Technical Consultant specialised in Humid Tanning Processes at CIATEC's Technological Solutions Department. The chemical composition of most of the vegetable extracts contains tannins<span style="font-size: 8pt;"><a href="#_ftn11" name="_ftnref11">11</a>.</span></p>
<p>The interaction of tannins with collagen is what will give us the flexible, resistant and durable result characteristic of leather. Collagen is a protein found in animal skin that is sought to be preserved in the tanning process. Tannins can bind to collagen. This union allows to stabilise the collagen so that it does not decompose. If a material has tannins, it can always stabilise the collagen<a href="#_ftn12" name="_ftnref12"><sup>12</sup></a>, explained researcher Nieto.</p>
<p>Tanners make it possible to transform skin into leather, and tannins fulfil that function.</p>
<p>Tannins have a bitter taste<span style="font-size: 8pt;"><a href="#_ftn13" name="_ftnref13">13</a> </span>and can be present in any part of the plant, the stem, the bark, the root, the leaves, and even in the fruits and seeds<a href="#_ftn14" name="_ftnref14"><sup>14</sup></a> <a href="#_ftn15" name="_ftnref15"><sup>15</sup></a> <a href="#_ftn16" name="_ftnref16"><sup>16</sup></a> <a href="#_ftn17" name="_ftnref17"><sup>17</sup></a>. Although each plant has a different and particular concentration,<a href="#_ftn18" name="_ftnref18"><sup>18</sup></a> if it contains tannins it can be used as a tanning agent.<a href="#_ftn19" name="_ftnref19"><sup>19</sup></a>That is to say, when a plant has tannins, they can be extracted and cause the reaction (tanning) that we need for the tanning process.<a href="#_ftn20" name="_ftnref20"><sup>20</sup></a></p>
<p>Although there is no minimum concentration of tannins required,<a href="#_ftn21" name="_ftnref21"><sup>21</sup></a> <a href="#_ftn22" name="_ftnref22"><sup>22</sup></a> it is ideal that a plant has the maximum concentration possible to make the extraction worthwhile and sustainable.<a href="#_ftn23" name="_ftnref23"><sup>23</sup></a>The species with the highest amount of tannins are very profitable. If a plant is low in quantity, it is less affordable<a href="#_ftn24" name="_ftnref24"><sup>24</sup></a>, CIATEC researchers explained to us.</p>
<p>However, plants with less tannins can still be used for tanning, they simply need to be used in greater concentration and with a greater amount of product.<a href="#_ftn25" name="_ftnref25"><sup>25</sup></a>It can even be combined with some other tanning substance to enhance its effect.<a href="#_ftn26" name="_ftnref26"><sup>26</sup></a> <a href="#_ftn27" name="_ftnref27"><sup>27</sup></a></p>
<p>If a plant has less than 5% tannin, its extraction is not worthwhile<a href="#_ftn28" name="_ftnref28"><sup>28</sup></a> <a href="#_ftn29" name="_ftnref29"><sup>29</sup></a>, agree José León Montoya Valadez, Technical Consultant in Manufacturing Processes and José Martín Calvillo Mares, Technical Consultant focused on Dry Finishing of Leather at CIATEC.</p>
<p>An ideal presence of tannins would be around 70%, so that their extraction is profitable.<a href="#_ftn30" name="_ftnref30"><sup>30</sup></a>The most commercial products used for vegetable tanning, such as extracts from quebrachos (trees of the <em>Schinopsis</em> genus)<a href="#_ftn31" name="_ftnref31"><span style="font-size: 8pt;">31</span></a>, have a tannin content of between 70 and 80%.<a href="#_ftn32" name="_ftnref32"><sup>32</sup></a></p>
<p><strong>&nbsp;</strong>There are studies in which the effects of extracts from the leaf and stem of Mimosa tenuiflora (Willd.) <em>Poir </em>were<em> evaluated.</em> The results showed that the extract contains a total of 30.13 gallic mg of tannins per gram of extract. A total of 138.85 mg Gallic of tannins per gram of extract was found in the bark.<a href="#_ftn33" name="_ftnref33"><sup>33</sup></a>Other studies have shown almost 70% condensed tannins in the bark extract of <em>Mimosa tenuiflora</em>.<a href="#_ftn34" name="_ftnref34"><sup>34</sup></a></p>
<p>It is for this reason that the bark of tepezcohuite, the name in Mexico of the plant <em>Mimosa hostilis</em>, is ideal for vegetable tanning.</p>
<p id="how">&nbsp;</p>
<h2>How to extract the tannins from Mimosa hostilis?</h2>
<p>Since we have understood the importance of tannins in tanning, the first step is to extract the bark. It must be separated from the trunk without damaging the wood. Ideally, this should be done in a moderate manner and respecting the regeneration times of the bark.<a href="#_ftn35" name="_ftnref35"><sup>35</sup></a>Subsequently, it is crushed or mashed to form the smallest possible pieces<a href="#_ftn36" name="_ftnref36"><sup>36</sup></a>, explained María Alejandra Rivera Trasgallo, Advisor-Researcher in the Environmental Area of CIATEC.<a href="#_ftn37" name="_ftnref37"><sup>37</sup></a></p>
<p>The process of extracting the tannins is similar to making an infusion<a href="#_ftn38" name="_ftnref38"><sup>38</sup></a> <a href="#_ftn39" name="_ftnref39"><sup>39</sup></a>:</p>
<ol>
    <li>In a container with hot water small pieces of the bark are added so that the reaction takes place more quickly.</li>
    <li>It should be stirred constantly.<a href="#_ftn40" name="_ftnref40"><sup>40</sup></a>The change in colour of the water will indicate that the process is on the right track.<a href="#_ftn41" name="_ftnref41"><sup>41</sup></a></li>
    <li>It is filtered. This liquid already contains the tannins.<a href="#_ftn42" name="_ftnref42"><sup>42</sup></a></li>
    <li>Dry the infusion of tanning materials at a high temperature, which will result in a powder.<a href="#_ftn43" name="_ftnref43"><sup>43</sup></a></li>
</ol>
<p id="step">&nbsp;</p>
<h2>Step by step: Tanning the vegetable with Mimosa hostilis</h2>
<p><strong>1. Soaking</strong></p>
<p>When an animal is skinned, the skin is usually preserved with salt to prevent decomposition.<a href="#_ftn44" name="_ftnref44"><sup>44</sup></a> Freshly skinned, the skin contains 60 to 70% water. However, in its transfer to where the skin will be tanned, it gradually dehydrates.<a href="#_ftn45" name="_ftnref45"><sup>45</sup></a></p>
<p>To rehydrate it, it is placed in a container where it can be extended and a water bath is added. The amount of water must be 100% in relation to the weight of the skin.<a href="#_ftn46" name="_ftnref46"><sup>46</sup></a>For example, if a skin weighs 66 pounds, it should be soaked in approximately 6.6 gallons.<a href="#_ftn47" name="_ftnref47"><sup>47</sup></a></p>
<p>If the skin was preserved in salt, it should be soaked for 48 hours. If the skin does not acquire the desired flexibility, it can be soaked for another 24 hours. The water should be changed constantly until it is clean. Freshly flayed skin should be cleaned for 6 hours, and should be free of dirt, blood, meat and fat before soaking.<a href="#_ftn48" name="_ftnref48"><sup>48</sup></a></p>
<p>After soaking, the skin should be flexible and washed until the water is clean.<a href="#_ftn49" name="_ftnref49"><sup>49</sup></a>Once the process is finished, the used water is discarded.<a href="#_ftn50" name="_ftnref50"><sup>50</sup></a></p>
<p>&nbsp;</p>
<p><strong>2. Liming</strong></p>
<p>In the liming or depilation stage, the skin is spread out and placed in another bath with sodium sulphide and lime until it is completely covered<a href="#_ftn51" name="_ftnref51"><sup>51</sup></a> <a href="#_ftn52" name="_ftnref52"><sup>52</sup></a> for 72 hours.<a href="#_ftn53" name="_ftnref53"><sup>53</sup></a>The lime opens the skin fibres so that they can then receive the tanning substances.<a href="#_ftn54" name="_ftnref54"><sup>54</sup></a></p>
<p>After some time, the hair falls out on its own, leaving only the skin<a href="#_ftn55" name="_ftnref55"><sup>55</sup></a>, and its thickness will triple.<a href="#_ftn56" name="_ftnref56"><sup>56</sup></a> The water with hair must also be discarded after the process.<a href="#_ftn57" name="_ftnref57"><sup>57</sup></a></p>
<p>&nbsp;</p>
<p><strong>3. Defleshing</strong></p>
<p>Removing the skin consists of placing the skin with the external part down and removing the meat with the help of a blade until the desired thickness is achieved. The blade can also help to remove excess hair. At this stage, abundant water is needed to clean the skin.<a href="#_ftn58" name="_ftnref58"><sup>58</sup></a></p>
<p><strong>&nbsp;</strong></p>
<p><strong>4. Deliming</strong></p>
<p>Deliming involves removing the lime left over from the liming process.<a href="#_ftn59" name="_ftnref59"><sup>59</sup></a>Once the skin is free of scales and hair, it is placed in another bath for 72 hours, until there is no more lime left. While soaking, the skin should be removed, scrubbed and scraped every 12 hours. The water must be changed for each wash.<a href="#_ftn60" name="_ftnref60"><sup>60</sup></a></p>
<p>Ammonium sulphate, sodium bisulphite or commercial deliming agents can be used to assist in this process.<a href="#_ftn61" name="_ftnref61"><sup>61</sup></a></p>
<p>&nbsp;</p>
<p><strong>5. Acidification</strong></p>
<p>During this whole process the pH of the skin has been modified. For a better effect of the tanning materials, it is important to confirm that the leather has a pH of 5.<a href="#_ftn62" name="_ftnref62"><sup>62</sup></a> One way to do this is with formic acid.<a href="#_ftn63" name="_ftnref63"><sup>63</sup></a></p>
<p>&nbsp;</p>
<p><strong>6. Tanning</strong></p>
<p>At this stage, the leather will be ready. Clean water is applied with a minimum load of the crust, which will give colour to the first layer of the skin. The skin is then immersed with the outer side up in another bath of dye from the bark of <em>Mimosa tenuiflora</em> (syn. <em>Mimosa hostilis</em>).<a href="#_ftn64" name="_ftnref64"><sup>64</sup></a></p>
<p>It should be removed three times a day for 72 hours. When the main face of the skin is already painted, the position is reversed, the inner face is placed upwards, and a strong charge of bark is added.<a href="#_ftn65" name="_ftnref65"><sup>65</sup></a></p>
<p>It can be seen that the tannins have already penetrated the skin when it acquires the colour of the vegetable tanning agent, in this case, the colour of <em>Mimosa hostilis</em><a href="#_ftn66" name="_ftnref66"><sup>66</sup></a> which generates reddish to ochre tones.</p>
<p>Afterwards, a last wash is carried out, or the skin is left to soak in water and soap for three hours. After this last wash, you will have the leather ready.<a href="#_ftn67" name="_ftnref67"><sup>67</sup></a></p>
<p id="one">&nbsp;</p>
<h2>One last tip: How to preserve the fur with Mimosa hostilis</h2>
<p>If you want to keep the hair, the tanning process will be the same, simply skip the liming stage (step 2) and the deliming stage (step 4), as you will not be using lime. After soaking, the skin is removed, the pH is checked and the tanning stage is carried out, preserving the hair.<a href="#_ftn68" name="_ftnref68"><sup>68</sup></a> <a href="#_ftn69" name="_ftnref69"><sup>69</sup></a></p>
<p>Optionally, the hair can be prepared from the soaking stage. Use a little formic acid to strengthen the hair with the skin and prevent it from falling out during the whole process.<a href="#_ftn70" name="_ftnref70"><sup>70</sup></a></p>
<p>&nbsp;</p>
<p style="text-align: center;"><strong>Are you ready to try it? Learn about the experience of those who have done this procedure.&nbsp;</strong></p>
<hr>
<div style="border: 1px solid #ccc; padding: 20px 27px; margin-bottom: 38px;">
    <h4 style="margin-top: 11px; margin-bottom: 14px;">Acknowledgements</h4>
    <ul>
        <li>Center for Applied Innovation in Competitive Technologies (CIATEC), part of the Network of Public Centers of the National Council for Science and Technology (CONACYT) of Mexico.</li>
        <li>Benjamín Aguilar Ruíz, Specialised Technical Consultant in Humid Tanning Processes of the Technological Solutions Department of CIATEC.</li>
        <li>José León Montoya Valadez, Technical Consultant in Manufacturing Processes of the Technological Solutions Department of CIATEC.</li>
        <li>José Martín Calvillo Mares, Technical Consultant focused on Dry Leather Finishing in the Technological Solutions Department of CIATEC.</li>
        <li>María Alejandra Rivera Trasgallo, Advisor-Researcher in the Environmental Area of the Technological Solutions Department at CIATEC.</li>
        <li>Yolanda Nieto Urroz, Technical Consultant in Tanning Processes in the Technology Transfer Department of CIATEC.</li>
    </ul>
</div>
<div style="border: 1px solid #ccc; padding: 11px 27px;">
    <h4 style="margin-bottom: 16px;">References</h4>
    <p><a href="#_ftnref1" name="_ftn1"> 1. </a> Duque, O. (2007).<span style="color: #333333;"> <a style="color: #333333;" href="http://lasallista.edu.co/fxcul/media/pdf/RevistaLimpia/vol2n2/PL_V2N2_47-56_cuero.pdf">http://lasallista.edu.co/fxcul/media/pdf/RevistaLimpia/vol2n2/PL_V2N2_47-56_cuero.pdf</a></span></p>
    <p><a href="#_ftnref2" name="_ftn2"> 2. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref3" name="_ftn3"> 3. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref4" name="_ftn4"> 4. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref5" name="_ftn5"> 5. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref6" name="_ftn6"> 6. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref7" name="_ftn7"> 7. </a> Gómez, E. (2004). Comparación del porcentaje de extracto tánico de la corteza y de la madera de encino (Quercus tristis Liebm) proveniente de un bosque natural.&nbsp; Universidad de San Carlos de Guatemala. Facultad de Ingeniería. Escuela de Ingeniería Química. Guatemala, noviembre 2004.</p>
    <p><a href="#_ftnref8" name="_ftn8"> 8. </a>Gómez, E. (2004).</p>
    <p><a href="#_ftnref9" name="_ftn9"> 9. </a> Gómez, E. (2004).</p>
    <p><a href="#_ftnref10" name="_ftn10"> 10. </a> Gómez, E. (2004).</p>
    <p><a href="#_ftnref11" name="_ftn11"> 11. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
    <p><a href="#_ftnref12" name="_ftn12"> 12. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref13" name="_ftn13"> 13. </a> Gómez, E. (2007).</p>
    <p><a href="#_ftnref14" name="_ftn14"> 14. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref15" name="_ftn15"> 15. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref16" name="_ftn16"> 16. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref17" name="_ftn17"> 17. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
    <p><a href="#_ftnref18" name="_ftn18"> 18. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref19" name="_ftn19"> 19. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
    <p><a href="#_ftnref20" name="_ftn20"> 20. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref21" name="_ftn21"> 21. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref22" name="_ftn22"> 22. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref23" name="_ftn23"> 23. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref24" name="_ftn24"> 24. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
    <p><a href="#_ftnref25" name="_ftn25"> 25. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref26" name="_ftn26"> 26. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref27" name="_ftn27"> 27. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref28" name="_ftn28"> 28. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref29" name="_ftn29"> 29. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref30" name="_ftn30"> 30. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
    <p><a href="#_ftnref31" name="_ftn31"> 31. </a> Barberis, I. M. et al, (2012). Biología de especies australes: Schinopsis balansae Engl. (Anarcadiacea). <em>Kurtziana</em></p>
    <p><a href="#_ftnref32" name="_ftn32"> 32. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref33" name="_ftn33"> 33. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://www.scielo.br/scielo.php?script=sci_arttext&amp;pid=S1984-29612011000200011&amp;lng=en&amp;nrm=iso&amp;tlng=en">Oliveira, L. M.; Bevilaqua, C. M. (2011). “Effect of six tropical tanniferous plant extracts on larval exsheathment of Haemonchus contortus.” Rev Bras Parasitol Vet 20(2): 155-160.</a></span></p>
    <p><a href="#_ftnref34" name="_ftn34"> 34. </a> <span style="color: #333333;">Anton, R., Jiang, Y. (1993). “Pharmacognosy of Mimosa tenuiflora (Willd.) Poiret.” J Ethnopharmacol 38(2-3): 153-157</span></p>
    <p><a href="#_ftnref35" name="_ftn35"> 35. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
    <p><a href="#_ftnref36" name="_ftn36"> 36. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
    <p><a href="#_ftnref37" name="_ftn37"> 37. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
    <p><a href="#_ftnref38" name="_ftn38"> 38. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref39" name="_ftn39"> 39. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref40" name="_ftn40"> 40. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref41" name="_ftn41"> 41. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
    <p><a href="#_ftnref42" name="_ftn42"> 42. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref43" name="_ftn43"> 43. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref44" name="_ftn44"> 44. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
    <p><a href="#_ftnref45" name="_ftn45"> 45. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
    <p><a href="#_ftnref46" name="_ftn46"> 46. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
    <p><a href="#_ftnref47" name="_ftn47"> 47. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
    <p><a href="#_ftnref48" name="_ftn48"> 48. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
    <p><a href="#_ftnref49" name="_ftn49"> 49. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
    <p><a href="#_ftnref50" name="_ftn50"> 50. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
    <p><a href="#_ftnref51" name="_ftn51"> 51. </a><span style="color: #333333;"> <a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
    <p><a href="#_ftnref52" name="_ftn52"> 52. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
    <p><a href="#_ftnref53" name="_ftn53"> 53. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
    <p><a href="#_ftnref54" name="_ftn54"> 54. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
    <p><a href="#_ftnref55" name="_ftn55"> 55. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
    <p><a href="#_ftnref56" name="_ftn56"> 56. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
    <p><a href="#_ftnref57" name="_ftn57"> 57. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
    <p><a href="#_ftnref58" name="_ftn58"> 58. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
    <p><a href="#_ftnref59" name="_ftn59"> 59. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
    <p><a href="#_ftnref60" name="_ftn60"> 60. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
    <p><a href="#_ftnref61" name="_ftn61"> 61. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
    <p><a href="#_ftnref62" name="_ftn62"> 62. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
    <p><a href="#_ftnref63" name="_ftn63"> 63. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
    <p><a href="#_ftnref64" name="_ftn64"> 64. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
    <p><a href="#_ftnref65" name="_ftn65"> 65. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
    <p><a href="#_ftnref66" name="_ftn66"> 66. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
    <p><a href="#_ftnref67" name="_ftn67"> 67. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
    <p><a href="#_ftnref68" name="_ftn68"> 68. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref69" name="_ftn69"> 69. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
    <p><a href="#_ftnref70" name="_ftn70"> 70. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
</div>