<p><img src="{{media url=&quot;wysiwyg/BLOGS_HEADER_5.jpg&quot;}}" alt="Mimosa Company" width="1200"></p>
<p>El curtido de piel con métodos vegetales es una opción más amigable con el ambiente, creativa y artesanal. Te explicamos cómo curtir piel con Mimosa hostilis.</p>
<h2>Contenido</h2>
<ol>
    <li><a href="#the"> The chemistry and tradition behind Mimosa hostilis tanning </a></li>
    <li><a href="#how"> ¿Cómo extraer los taninos de Mimosa hostilis? </a></li>
    <li><a href="#step"> Paso a paso: Curtido al vegetal con Mimosa hostilis </a></li>
    <li><a href="#one"> Un último tip: Cómo conservar el pelaje con Mimosa hostilis </a></li>
</ol>
<p>&nbsp;</p>
<p>El extracto de <em>Mimosa hostilis </em>tiene propiedades ideales para curtir piel. Esto lo saben algunos artesanos, comerciantes, investigadores y artistas, sin embargo, la información disponible es limitada. Para explorar más este uso, nos dimos a la tarea de entrevistar a expertos, consultar fuentes y compartir contigo esta técnica. ¿Lo intentarías?</p>
<p>Como sucede con el teñido de textiles, usar <em>Mimosa tenuiflora </em>(<em>syn.</em>) puede ser una técnica más amigable con el ambiente y, por lo tanto, una alternativa a técnicas que incluyen cromo, aluminio, circonio, entre otros químicos, como ácido sulfúrico<a href="#_ftn1" name="_ftnref1"><span style="font-size: 8pt;">1</span></a>. La técnica en la que se usan derivados de plantas se conoce como “curtido al vegetal” mientras que aquella en la que usan los químicos mencionados, “curtido mineral”. Las diferencias entre una técnica y otra tienen pros y contras.</p>
<p>En el mercado, el curtido de piel al vegetal es apreciado porque de él se obtienen cueros más pesados y gruesos<a href="#_ftn2" name="_ftnref2"><sup>2</sup></a>, los cuales se cotizan mejor, pues se venden por peso<a href="#_ftn3" name="_ftnref3"><sup>3</sup></a> <a href="#_ftn4" name="_ftnref4"><sup>4</sup></a>, nos explicaron expertos del Centro de Innovación Aplicada en Tecnologías Competitivas (CIATEC), una institución ubicada en la ciudad de León, en el centro de México, reconocida por su gran industria de calzado y otros productos de piel.</p>
<p>Los cueros que resultan de la técnica vegetal son muy aptos para realizarles grabados, los aceptan fácilmente y los conservan, algo que no ocurre con el curtido al mineral<a href="#_ftn5" name="_ftnref5"><sup>5</sup></a>, nos explicó Yolanda Nieto Urroz, Consultora Técnica en Procesos de Curtido en el Departamento de Transferencia de Tecnología del CIATEC. ¿Quieres ideas de cómo usar esta cualidad a tu favor? Esta característica resulta útil para imprimir firmas o sellos en los cueros.</p>
<p>Algo que no debes olvidar es que una desventaja de la técnica con plantas se presenta con la exposición a la luz. Con el tiempo, el cuero curtido al vegetal se oxida y podría cambiar de color y oscurecerse.<a href="#_ftn6" name="_ftnref6"><sup>6</sup></a></p>
<p id="the">&nbsp;</p>
<h2>La química y tradición detrás del curtido con Mimosa hostilis</h2>
<p>¿Se puede curtir piel con <em>Mimosa tenuiflora</em>? La respuesta sencilla es <em>sí</em>, pero detrás están los taninos, sustancias clave en el proceso del curtido y de la composición de los extractos de <em>Mimosa hostilis</em> y su interacción con el colágeno de la piel.</p>
<p>Esta interacción ha sido conocida desde la antigüedad, cuando las civilizaciones observaron que la piel que entraba en contacto con ciertas cortezas se hacía resistente y evitaba la putrefacción<span style="font-size: 8pt;"><a href="#_ftn7" name="_ftnref7">7</a></span>.</p>
<p>Se han encontrado antecedentes de curtido desde el año 1000 A.C.<span style="font-size: 8pt;"><a href="#_ftn8" name="_ftnref8">8</a></span>,&nbsp; en la antigua Fenicia se utilizaban pieles finamente tratadas y las tribus norteamericanas precolombinas curtían piel de búfalo, dominando la técnica con plantas que trascendió a Europa. Todas esas técnicas coinciden en manejar la propiedad astringente de los extractos. Aunque fue hasta finales del siglo XVIII cuando en Francia se descubrieron los químicos que curtían la piel: los taninos<span style="font-size: 8pt;"><a href="#_ftn9" name="_ftnref9">9</a></span>.</p>
<p>Vamos a hablar de química. Los taninos son ácidos muy astringentes y son resultado de la combinación de un fenol y un azúcar<span style="font-size: 8pt;"><a href="#_ftn10" name="_ftnref10">10</a></span>. El tanino es un compuesto orgánico polifuncional formado por carbono, hidrógeno y oxígeno, describió Benjamín Aguilar Ruíz, Consultor Técnico Especializado en Procesos Húmedos de Curtido del Departamento de Soluciones Tecnológicas del CIATEC. La composición química de la gran mayoría de los extractos vegetales contiene taninos<span style="font-size: 8pt;"><a href="#_ftn11" name="_ftnref11">11</a></span> .</p>
<p>La interacción de los taninos con el colágeno es lo que nos dará el resultado flexible, resistente y durable característico del cuero. El colágeno es una proteína hallada en la piel animal que se busca conservar en el proceso de curtido. Los taninos pueden unirse al colágeno. Esa unión permite estabilizar al colágeno para que no se descomponga. Si un material tiene taninos, siempre podrá estabilizar el colágeno<a href="#_ftn12" name="_ftnref12"><sup>12</sup></a>, nos explicó la investigadora Nieto.</p>
<p>Los curtientes hacen posible la transformación de la piel en cuero y los taninos cumplen esa función.</p>
<p>Los taninos tienen un gusto amargo<span style="font-size: 8pt;"><a href="#_ftn13" name="_ftnref13">13</a></span> y pueden estar presentes en cualquier parte de la planta, el tallo, la corteza, la raíz, las hojas, e incluso en los frutos y semillas<a href="#_ftn14" name="_ftnref14"><sup>14</sup></a> <a href="#_ftn15" name="_ftnref15"><sup>15</sup></a> <a href="#_ftn16" name="_ftnref16"><sup>16</sup></a> <a href="#_ftn17" name="_ftnref17"><sup>17</sup></a>. Aunque cada planta tiene una concentración diferente y particular,<a href="#_ftn18" name="_ftnref18"><sup>18</sup></a> si contiene taninos puede utilizarse como curtiente.<a href="#_ftn19" name="_ftnref19"><sup>19</sup></a> Es decir, cuando una planta tiene taninos, pueden extraerse y provocar la reacción (curtiente) que necesitamos para el proceso de curtido. <a href="#_ftn20" name="_ftnref20"><sup>20</sup></a></p>
<p>Aunque no existe una concentración mínima de taninos necesaria,<a href="#_ftn21" name="_ftnref21"><sup>21</sup></a> <a href="#_ftn22" name="_ftnref22"><sup>22</sup></a> es ideal que una planta tenga la máxima concentración posible para que la extracción valga la pena y sea sostenible.<a href="#_ftn23" name="_ftnref23"><sup>23</sup></a> Las especies que tienen mayor cantidad de taninos resultan muy rentables. Si una planta tiene poca cantidad, es menos costeable<a href="#_ftn24" name="_ftnref24"><sup>24</sup></a>, nos explicaron los investigadores del CIATEC.</p>
<p>Sin embargo, plantas con menor presencia de taninos aún pueden utilizarse para curtir, simplemente necesitan utilizarse en mayor concentración y con mayor cantidad de producto.<a href="#_ftn25" name="_ftnref25"><sup>25</sup></a> Incluso puede combinarse con alguna otra sustancia curtiente para potenciar su efecto.<a href="#_ftn26" name="_ftnref26"><sup>26</sup></a> <a href="#_ftn27" name="_ftnref27"><sup>27</sup></a></p>
<p>Si una planta tiene una cantidad de tanino menor al 5%, su extracción no vale la pena<a href="#_ftn28" name="_ftnref28"><sup>28</sup></a> <a href="#_ftn29" name="_ftnref29"><sup>29</sup></a>, coinciden José León Montoya Valadez, Consultor Técnico en Procesos de Manufactura y José Martín Calvillo Mares, Consultor Técnico enfocado al Acabado en Seco de Cueros del CIATEC.</p>
<p>Una presencia idónea de taninos sería alrededor del 70%, para que su extracción sea rentable.<a href="#_ftn30" name="_ftnref30"><sup>30</sup></a> Los productos más comerciales con los que se realiza el curtido al vegetal, como los extractos de quebrachos (árboles del género <em>Schinopsis</em>)<span style="font-size: 8pt;"><a href="#_ftn31" name="_ftnref31">31</a></span>, tienen una cantidad de taninos de entre 70 y 80%.<a href="#_ftn32" name="_ftnref32"><sup>32</sup></a></p>
<p><strong>&nbsp;</strong>Existen estudios en los cuales se evaluaron los efectos de los extractos de la hoja y tallo de <em>Mimosa tenuiflora</em> <em>(Willd.) Poir.</em> Los resultados arrojaron que el extracto contiene un total de 30.13 mg gálicos de taninos por cada gramo de extracto. En la corteza se hallaron un total de 138.85 mg gálicos de taninos por cada gramo de extracto.<a href="#_ftn33" name="_ftnref33"><sup>33</sup></a> Otros estudios demostraron la existencia de casi un 70% de taninos condensados en el extracto de la corteza de <em>Mimosa tenuiflora</em>.<a href="#_ftn34" name="_ftnref34"><sup>34</sup></a></p>
<p>Es por esta razón que la corteza de tepezcohuite, nombre en México de la planta <em>Mimosa hostilis</em>, es ideal para realizar curtido al vegetal.</p>
<p id="how">&nbsp;</p>
<h2>¿Cómo extraer los taninos de Mimosa hostilis?</h2>
<p>Ya que hemos comprendido la importancia de los taninos en el curtido, el primer paso es la extracción de la corteza. Debe separarse del tronco sin dañar la madera. Idealmente se debe hacer de manera moderada y respetando los tiempos de regeneración de la corteza.<a href="#_ftn35" name="_ftnref35"><sup>35</sup></a> Posteriormente, se tritura o machaca hasta formar los pedazos más pequeños posibles<a href="#_ftn36" name="_ftnref36"><sup>36</sup></a>, nos explicó María Alejandra Rivera Trasgallo, Asesora-Investigadora en el Área de Ambiental del CIATEC.<a href="#_ftn37" name="_ftnref37"><sup>37</sup></a></p>
<p>El proceso para extraer los taninos es similar a hacer una infusión<a href="#_ftn38" name="_ftnref38"><sup>38</sup></a> <a href="#_ftn39" name="_ftnref39"><sup>39</sup></a>:</p>
<ol>
    <li>En un recipiente se pone agua caliente y se agregan trozos pequeños de la corteza para que la reacción se lleve a cabo más rápidamente.</li>
    <li>Se debe revolver constantemente.<a href="#_ftn40" name="_ftnref40"><sup>40</sup></a> El cambio de color del agua nos indicará que el proceso va por buen camino.<a href="#_ftn41" name="_ftnref41"><sup>41</sup></a></li>
    <li>Se filtra. Este líquido ya contiene los taninos.<a href="#_ftn42" name="_ftnref42"><sup>42</sup></a></li>
    <li>Secar a alta temperatura la infusión de materiales curtientes, lo que nos dará como resultado un polvo.<a href="#_ftn43" name="_ftnref43"><sup>43</sup></a></li>
</ol>
<p id="step">&nbsp;</p>
<h2>Paso a paso: Curtido al vegetal con Mimosa hostilis</h2>
<p><strong>1. Remojo</strong></p>
<p>Cuando un animal es desollado, la piel suele conservarse con sal para evitar su descomposición.<a href="#_ftn44" name="_ftnref44"><sup>44</sup></a> Recién desollada, la piel contiene entre un 60 y 70% de agua. Sin embargo, en su traslado a donde se curtirá la piel, poco a poco se deshidrata.<a href="#_ftn45" name="_ftnref45"><sup>45</sup></a></p>
<p>Para rehidratarla, se coloca en un recipiente donde quepa extendida y se le pone un baño de agua. La cantidad de agua debe ser de un 100% respecto al peso de la piel.<a href="#_ftn46" name="_ftnref46"><sup>46</sup></a> Por ejemplo, si una piel pesa 30 kilos, debe remojarse en 30 litros aproximadamente.<a href="#_ftn47" name="_ftnref47"><sup>47</sup></a></p>
<p>Si la piel fue conservada en sal se debe remojar durante 48 horas. En caso de que la piel no adquiera la flexibilidad deseada, puede remojarse 24 horas más. El agua debe cambiarse constantemente hasta que quede limpia. La piel recién desollada debe recibir una limpieza de 6 horas, debe quedar libre de suciedad, sangre, carne y grasa antes del remojo.<a href="#_ftn48" name="_ftnref48"><sup>48</sup></a></p>
<p>Al finalizar el remojo la piel debe estar flexible y lavarse hasta que el agua quede limpia.<a href="#_ftn49" name="_ftnref49"><sup>49</sup></a> Una vez terminado el proceso, el agua usada se desecha.<a href="#_ftn50" name="_ftnref50"><sup>50</sup></a></p>
<p><strong>2. Pelambre</strong></p>
<p>En la etapa de pelambre o depilado, la piel se extiende y se pone en otro baño con sulfuro de sodio y cal hasta quedar cubierta por completo<a href="#_ftn51" name="_ftnref51"><sup>51</sup></a> <a href="#_ftn52" name="_ftnref52"><sup>52</sup></a> durante 72 horas.<a href="#_ftn53" name="_ftnref53"><sup>53</sup></a> La cal abre las fibras de la piel para que después puedan recibir las sustancias curtientes.<a href="#_ftn54" name="_ftnref54"><sup>54</sup></a></p>
<p>Al cabo de un tiempo, el pelo se cae solo y queda únicamente la piel<a href="#_ftn55" name="_ftnref55"><sup>55</sup></a> y su grosor se triplicará.<a href="#_ftn56" name="_ftnref56"><sup>56</sup></a> El agua con pelo también se debe desechar terminado el proceso.<a href="#_ftn57" name="_ftnref57"><sup>57</sup></a></p>
<p><strong>3. Descarne</strong></p>
<p>El desencarne consiste en colocar la piel con la parte externa hacia abajo y retirar la carne con ayuda de una cuchilla hasta que se tenga el grosor deseado. La cuchilla también puede ayudar a retirar el pelo sobrante. En esta etapa se necesita agua abundante para limpiar la piel.<a href="#_ftn58" name="_ftnref58"><sup>58</sup></a></p>
<p><strong>&nbsp;</strong><strong>4. Desencalado</strong></p>
<p>El desencalado implica eliminar la cal que quedó del proceso de pelambre.<a href="#_ftn59" name="_ftnref59"><sup>59</sup></a> Una vez que no tenga escamas ni pelo, la piel se pone en otro baño durante 72 horas, hasta que no haya restos de cal. Mientras se remoja, la piel debe removerse, fregarse y rasparse cada 12 horas. Por cada lavado se debe cambiar el agua.<a href="#_ftn60" name="_ftnref60"><sup>60</sup></a></p>
<p>Para ayudar en este proceso se puede utilizar sulfato de amonio, bisulfito de sodio o desencalantes comerciales.<a href="#_ftn61" name="_ftnref61"><sup>61</sup></a></p>
<p><strong>5. Acidificación</strong></p>
<p>Durante todo este proceso se ha modificado el pH de la piel. Para un mejor efecto de los materiales curtientes, es importante confirmar que la piel tenga un pH de 5.<a href="#_ftn62" name="_ftnref62"><sup>62</sup></a> Una manera de conseguirlo es con ácido fórmico.<a href="#_ftn63" name="_ftnref63"><sup>63</sup></a></p>
<p><strong>6. Curtido</strong></p>
<p><strong>&nbsp;</strong>En este paso, el cuero quedará listo. Se coloca agua limpia con una carga mínima de la corteza, que dará color a la primera capa de la piel. La piel se sumerge con la cara externa hacia arriba en otro baño de tintura de la corteza de <em>Mimosa tenuiflora</em> (syn. <em>Mimosa hostilis</em>).<a href="#_ftn64" name="_ftnref64"><sup>64</sup></a></p>
<p>Debe removerse tres veces al día durante 72 horas. Cuando la cara principal de la piel ya está pintada se invierte la posición, la cara interna se coloca hacia arriba, y se agrega una carga fuerte de corteza.<a href="#_ftn65" name="_ftnref65"><sup>65</sup></a></p>
<p>Se puede ver que los taninos ya penetraron en la piel cuando ésta adquiere el color del curtiente vegetal, en este caso, del color de <em>Mimosa hostilis</em><a href="#_ftn66" name="_ftnref66"><sup>66</sup></a></p>
<p>Después se realiza un último lavado, o se deja la piel en remojo de agua y jabón durante tres horas. Después de este último lavado, tendrás listo el cuero.<a href="#_ftn67" name="_ftnref67"><sup>67</sup></a></p>
<p id="one">&nbsp;</p>
<h2>Un último tip: Cómo conservar el pelaje con Mimosa hostilis</h2>
<p>Si lo que quieres es mantener el pelo, el proceso de curtido será el mismo, simplemente se omite la etapa de pelambre (paso 2) y la de desencalado (paso 4), ya que no utilizarás cal. Después del remojo se hace el descarne, se verifica el pH y se procede a hacer la etapa de curtido, conservando el pelaje.<a href="#_ftn68" name="_ftnref68"><sup>68</sup></a> <a href="#_ftn69" name="_ftnref69"><sup>69</sup></a></p>
<p>Opcionalmente, el pelo puede prepararse desde la etapa de remojo. Utiliza un poco de ácido fórmico para reforzar el pelo con la piel y evitar que se caiga durante todo el proceso.<a href="#_ftn70" name="_ftnref70"><sup>70</sup></a></p>
<p>&nbsp;</p>
<p style="text-align: center;"><strong>¿Estás listo para intentarlo? Conoce la experiencia de quienes han hecho este procedimiento.&nbsp;</strong></p>
<hr>
<div style="border: 1px solid #ccc; padding: 20px 27px; margin-bottom: 38px;">
<h4 style="margin-top: 11px; margin-bottom: 14px;">Agradecimientos</h4>
<ul>
    <li>Centro de Innovación Aplicada en Tecnologías Competitivas (CIATEC), parte de la Red de Centros Públicos del Consejo Nacional de Ciencia y Tecnología (CONACYT) de México.</li>
    <li>Benjamín Aguilar Ruíz, Consultor Técnico Especializado en Procesos Húmedos de Curtido del Departamento de Soluciones Tecnológicas del CIATEC.</li>
    <li>José León Montoya Valadez, Consultor Técnico en Procesos de Manufactura en el Departamento de Soluciones Tecnológicas del CIATEC.</li>
    <li>José Martín Calvillo Mares, Consultor Técnico enfocado al Acabado en Seco de Cueros en el Departamento de Soluciones Tecnológicas del CIATEC.</li>
    <li>María Alejandra Rivera Trasgallo, Asesora-Investigadora en el Área de Ambiental de la Dirección de Soluciones Tecnológicas del CIATEC.</li>
    <li>Yolanda Nieto Urroz, Consultora Técnica en Procesos de Curtido en el Departamento de Transferencia de Tecnología del CIATEC.</li>
</ul>
</div>
<div style="border: 1px solid #ccc; padding: 11px 27px;">
<h4 style="margin-bottom: 16px;">Referencias</h4>
<p><a href="#_ftnref1" name="_ftn1"> 1. </a> Duque, O. (2007).<span style="color: #333333;"> <a style="color: #333333;" href="http://lasallista.edu.co/fxcul/media/pdf/RevistaLimpia/vol2n2/PL_V2N2_47-56_cuero.pdf">http://lasallista.edu.co/fxcul/media/pdf/RevistaLimpia/vol2n2/PL_V2N2_47-56_cuero.pdf</a></span></p>
<p><a href="#_ftnref2" name="_ftn2"> 2. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref3" name="_ftn3"> 3. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref4" name="_ftn4"> 4. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref5" name="_ftn5"> 5. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref6" name="_ftn6"> 6. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref7" name="_ftn7">7.</a> Gómez, E. (2004). Comparación del porcentaje de extracto tánico de la corteza y de la madera de encino (Quercus tristis Liebm) proveniente de un bosque natural.&nbsp; Universidad de San Carlos de Guatemala. Facultad de Ingeniería. Escuela de Ingeniería Química. Guatemala, noviembre 2004.</p>
<p><a href="#_ftnref8" name="_ftn8">8.</a> Gómez, E. (2004).</p>
<p><a href="#_ftnref9" name="_ftn9">9.</a> Gómez, E. (2004).</p>
<p><a href="#_ftnref10" name="_ftn10">10.</a> Gómez, E. (2004).</p>
<p><a href="#_ftnref11" name="_ftn11"> 11. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref12" name="_ftn12"> 12. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref13" name="_ftn13"> 13. </a> Gómez, E. (2007).</p>
<p><a href="#_ftnref14" name="_ftn14"> 14. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref15" name="_ftn15"> 15. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref16" name="_ftn16"> 16. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref17" name="_ftn17"> 17. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref18" name="_ftn18"> 18. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref19" name="_ftn19"> 19. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref20" name="_ftn20"> 20. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref21" name="_ftn21"> 21. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref22" name="_ftn22"> 22. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref23" name="_ftn23"> 23. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref24" name="_ftn24"> 24. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref25" name="_ftn25"> 25. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref26" name="_ftn26"> 26. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref27" name="_ftn27"> 27. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref28" name="_ftn28"> 28. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref29" name="_ftn29"> 29. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref30" name="_ftn30"> 30. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref31" name="_ftn31"> 31. </a> Barberis, I. M. et al, (2012). Biología de especies australes: Schinopsis balansae Engl. (Anarcadiacea). <em>Kurtziana</em></p>
<p><a href="#_ftnref32" name="_ftn32"> 32. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref33" name="_ftn33"> 33. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://www.scielo.br/scielo.php?script=sci_arttext&amp;pid=S1984-29612011000200011&amp;lng=en&amp;nrm=iso&amp;tlng=en">Oliveira, L. M.; Bevilaqua, C. M. (2011). “Effect of six tropical tanniferous plant extracts on larval exsheathment of Haemonchus contortus.” Rev Bras Parasitol Vet 20(2): 155-160.</a></span></p>
<p><a href="#_ftnref34" name="_ftn34"> 34. </a> <span style="color: #333333;">Anton, R., Jiang, Y. (1993). “Pharmacognosy of Mimosa tenuiflora (Willd.) Poiret.” J Ethnopharmacol 38(2-3): 153-157</span></p>
<p><a href="#_ftnref35" name="_ftn35"> 35. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref36" name="_ftn36"> 36. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref37" name="_ftn37"> 37. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref38" name="_ftn38"> 38. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref39" name="_ftn39"> 39. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref40" name="_ftn40"> 40. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref41" name="_ftn41"> 41. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref42" name="_ftn42"> 42. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref43" name="_ftn43"> 43. </a> Nieto, Y. entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref44" name="_ftn44"> 44. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref45" name="_ftn45"> 45. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref46" name="_ftn46"> 46. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref47" name="_ftn47"> 47. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref48" name="_ftn48"> 48. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref49" name="_ftn49"> 49. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref50" name="_ftn50"> 50. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref51" name="_ftn51"> 51. </a><span style="color: #333333;"> <a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref52" name="_ftn52"> 52. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref53" name="_ftn53"> 53. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref54" name="_ftn54"> 54. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref55" name="_ftn55"> 55. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref56" name="_ftn56"> 56. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref57" name="_ftn57"> 57. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref58" name="_ftn58"> 58. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref59" name="_ftn59"> 59. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref60" name="_ftn60"> 60. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref61" name="_ftn61"> 61. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref62" name="_ftn62"> 62. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref63" name="_ftn63"> 63. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>
<p><a href="#_ftnref64" name="_ftn64"> 64. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref65" name="_ftn65"> 65. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref66" name="_ftn66"> 66. </a> Rivera, M.A., entrevista telefónica, 18 de junio de 2020</p>
<p><a href="#_ftnref67" name="_ftn67"> 67. </a> <span style="color: #333333;"><a style="color: #333333;" href="https://issuu.com/editorial_inia/docs/manualartesanias">Zapata, L. (2008). Manual práctico de curtido natural de cueros y producción de artesanías.</a></span></p>
<p><a href="#_ftnref68" name="_ftn68"> 68. </a> Montoya, J. L., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref69" name="_ftn69"> 69. </a> Calvillo, J. M., entrevista telefónica, 17 de junio de 2020</p>
<p><a href="#_ftnref70" name="_ftn70"> 70. </a> Aguilar, B., entrevista telefónica, 19 de junio de 2020</p>